In [1]:
import pandas as pd 
import numpy as np 
import os, sys
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import tree

In [4]:
#Extract the features and the predictors
data = pd.read_csv("/Users/vanshika/Downloads/dataset_fog_release/dataset_fog_release/dataset/feature.csv")
#predictors = data.drop(['name'], axis = 1)
target = data['0']
predictors = data.drop(['0'], axis = 1)#.as_matrix()


In [5]:
scaler = MinMaxScaler((-1, 1))
X = scaler.fit_transform(predictors)
Y = target

In [6]:
#Split training data 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .20, random_state = 7)

In [7]:
#create Decision Tree Classifier
model= tree.DecisionTreeClassifier()
model.fit(X_train, Y_train)

# make predictions
y_pred = model.predict(X_test)

# summarize the fit of the model
print("Decision Tree Classifier: ")
print("Accuracy: ",metrics.accuracy_score(Y_test, y_pred))
print("Classification summary: \n",metrics.classification_report(Y_test, y_pred))
print("Confusion matrix: \n",metrics.confusion_matrix(Y_test, y_pred))


Decision Tree Classifier: 
Accuracy:  0.988751850024667
Classification summary: 
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      8357
           1       0.99      0.99      0.99      1318
           2       0.91      0.87      0.89       460

    accuracy                           0.99     10135
   macro avg       0.96      0.95      0.96     10135
weighted avg       0.99      0.99      0.99     10135

Confusion matrix: 
 [[8321    8   28]
 [   8 1300   10]
 [  52    8  400]]


In [15]:
# saving model
import pickle

# Save the trained model as a pickle string.
saved_model = pickle.dump(model, open('/Users/vanshika/DecisionTree', 'wb'))

# Load the pickled model
m_from_pickle = pickle.load(open('/Users/vanshika/DecisionTree', 'rb'))

# Use the loaded pickled model to make predictions
m_from_pickle.predict(X_test)


array([1, 0, 0, ..., 2, 0, 0], dtype=int64)