In [1]:
import pandas as pd 
import numpy as np 
import os, sys
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import tree

In [2]:
#Extract the features and the predictors
data = pd.read_csv("/Users/vanshika/Downloads/dataset_fog_release/dataset_fog_release/dataset/data.csv")
predictors = data.drop(['name'], axis = 1)
predictors = predictors.drop(['Action'], axis = 1)#.as_matrix()
target = data['Action']

In [3]:
scaler = MinMaxScaler((-1, 1))
X = scaler.fit_transform(predictors)
Y = target

In [4]:
#Split training data 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .20, random_state = 7)

In [6]:
#create Decision Tree Classifier
model= tree.DecisionTreeClassifier()
model.fit(X_train, Y_train)

# make predictions
y_pred = model.predict(X_test)

# summarize the fit of the model
print("Decision Tree Classifier: ")
print("Accuracy: ",metrics.accuracy_score(Y_test, y_pred))
print("Classification summary: \n",metrics.classification_report(Y_test, y_pred))
print("Confusion matrix: \n",metrics.confusion_matrix(Y_test, y_pred))


Decision Tree Classifier: 
Accuracy:  0.9709595519413098
Classification summary: 
               precision    recall  f1-score   support

           0       0.98      0.99      0.98    542671
           1       0.98      0.99      0.99     86806
           2       0.72      0.62      0.67     30258

    accuracy                           0.97    659735
   macro avg       0.89      0.87      0.88    659735
weighted avg       0.97      0.97      0.97    659735

Confusion matrix: 
 [[535529    173   6969]
 [   108  86161    537]
 [ 10220   1152  18886]]
