In [1]:
import pandas as pd 
import numpy as np 
import os, sys
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier

In [3]:
#Extract the features and the predictors
data = pd.read_csv("/Users/vanshika/Downloads/dataset_fog_release/dataset_fog_release/dataset/feature.csv")
target = data['0']
# predictors = data.drop(['name'], axis = 1)
predictors = data.drop(['0'], axis = 1)#.as_matrix()


In [4]:
scaler = MinMaxScaler((-1, 1))
X = scaler.fit_transform(predictors)
Y = target

In [5]:
#Split training data 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .25, random_state = 7)

In [8]:
#Create the K-Nearest-Neighbors model
model = KNeighborsClassifier()
model.fit(X_train, Y_train)

# make predictions
y_pred = model.predict(X_test)

# summarize the fit of the model
print("k-Nearest Neighbor: ")
print("Accuracy: ",metrics.accuracy_score(Y_test, y_pred))
print("Classification summary:\n ",metrics.classification_report(Y_test, y_pred))
print("Confusion matrix: \n",metrics.confusion_matrix(Y_test, y_pred))

# Now we are gonna try fine-tuning KNeighborsCclassifier() aka beat 97.959% 

k-Nearest Neighbor: 
Accuracy:  0.9212250374930934
Classification summary:
                precision    recall  f1-score   support

           0       0.95      0.97      0.96     10456
           1       0.81      0.79      0.80      1627
           2       0.53      0.38      0.44       586

    accuracy                           0.92     12669
   macro avg       0.76      0.71      0.74     12669
weighted avg       0.92      0.92      0.92     12669

Confusion matrix: 
 [[10158   183   115]
 [  252  1290    85]
 [  246   117   223]]


In [9]:
# saving model
import pickle
#from sklearn.externals import joblib

# Save the trained model as a pickle string.
saved_model = pickle.dump(model, open('/Users/vanshika/knn', 'wb'))

# Load the pickled model
m_from_pickle = pickle.load(open('/Users/vanshika/knn', 'rb'))

# Use the loaded pickled model to make predictions
m_from_pickle.predict(X_test)
#joblib.dump(model, '/Users/vanshika/DecisionTree')


array([1, 0, 0, ..., 2, 0, 0], dtype=int64)

In [13]:
# import matplotlib.pyplot as plt
# import seaborn as sns
# from matplotlib.colors import ListedColormap

# h = 0.02  # step size in the mesh

# # Create color maps
# cmap_light = ListedColormap(["orange", "cyan", "cornflowerblue"])
# cmap_bold = ["darkorange", "c", "darkblue"]

# # Plot the decision boundary. For that, we will assign a color to each
# # point in the mesh [x_min, x_max]x[y_min, y_max].
# x_min, x_max = X_train[:, 0].min() - 1, X_train[:, 0].max() + 1
# y_min, y_max = X_train[:, 1].min() - 1, X_train[:, 1].max() + 1
# xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
# # Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
# Z=y_pred
# # Put the result into a color plot
# Z = Z.reshape(xx.shape)
# plt.figure(figsize=(8, 6))
# plt.contourf(xx, yy, Z, cmap=cmap_light)

# # Plot also the training points
# sns.scatterplot(
#     x=X_train[:, 0],
#     y=X_train[:, 1],
#     hue=iris.target_names[Y_train],
#     palette=cmap_bold,
#     alpha=1.0,
#     edgecolor="black",
# )
# plt.xlim(xx.min(), xx.max())
# plt.ylim(yy.min(), yy.max())
# plt.title( "3-Class classification")
# Z = model.predict(np.c_[xx.ravel(), yy.ravel()])

# plt.xlim(xx.min(), xx.max())
# plt.ylim(yy.min(), yy.max())
# plt.title(
#     "3-Class classification")
# # plt.xlabel(iris.feature_names[0])
# # plt.ylabel(iris.feature_names[1])

# plt.show()