In [1]:
import pandas as pd 
import numpy as np 
import os, sys
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from xgboost import XGBClassifier


In [2]:
#Extract the features and the predictors
data = pd.read_csv("/Users/vanshika/Downloads/dataset_fog_release/dataset_fog_release/dataset/feature.csv")
target = data['0']
predictors = data.drop(['0'], axis = 1)#.as_matrix()


In [3]:
scaler = MinMaxScaler((-1, 1))
X = scaler.fit_transform(predictors)
Y = target

In [4]:
#Split training data 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .14, random_state = 7)

In [5]:
# Train
model = XGBClassifier()
model.fit(X_train, Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=0, reg_alpha=0, ...)

In [12]:
# Evaluate
Y_hat = [round(yhat) for yhat in model.predict(X_test)]
print('Test set Accuracy: ',metrics.accuracy_score(Y_test, Y_hat)) # Test set accuracy
# Y_hat=[]
# Y_hat = [round(yhat) for yhat in model.predict(X)]
# print('Full set Accuracy: ',metrics.accuracy_score(Y, Y_hat)) # Full set accuracy

Test set Accuracy:  0.9826638477801268


In [14]:
print("Classification summary: \n",metrics.classification_report(Y_test, Y_hat))
print("Confusion matrix: \n",metrics.confusion_matrix(Y_test, Y_hat))


Classification summary: 
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      5878
           1       0.97      0.98      0.97       915
           2       0.96      0.74      0.83       302

    accuracy                           0.98      7095
   macro avg       0.97      0.90      0.93      7095
weighted avg       0.98      0.98      0.98      7095

Confusion matrix: 
 [[5853   15   10]
 [  18  897    0]
 [  64   16  222]]


In [15]:
from xgboost import Booster

model._Booster.save_model('modelXG.bin')

def load_xgb_model():
    _m = XGBClassifier()
    _b = Booster()
    _b.load_model('modelXG.bin')
    _m._Booster = _b
    return _m

model = load_xgb_model()