In [1]:
import pandas as pd 
import numpy as np 
import os, sys
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [3]:
#Extract the features and the predictors
data = pd.read_csv("/Users/vanshika/Downloads/dataset_fog_release/dataset_fog_release/dataset/feature.csv")
target = data['0']
# predictors = data.drop(['name'], axis = 1)
predictors = data.drop(['0'], axis = 1)#.as_matrix()


In [4]:
scaler = MinMaxScaler((-1, 1))
X = scaler.fit_transform(predictors)
Y = target

In [5]:
#Split training data 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .25, random_state = 7)

In [6]:
model= make_pipeline(StandardScaler(), SVC(gamma='auto'))
model.fit(X_train, Y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [7]:
y_pred= model.predict(X_test)

# summarize the fit of the model
print("Support Vector Machine Classifier: ")
print("Accuracy: ",metrics.accuracy_score(Y_test, y_pred))
print("Classification summary: \n",metrics.classification_report(Y_test, y_pred))
print("Confusion matrix: \n",metrics.confusion_matrix(Y_test, y_pred))


Support Vector Machine Classifier: 
Accuracy:  0.8804956981608651
Classification summary: 
               precision    recall  f1-score   support

           0       0.90      0.98      0.94     10456
           1       0.70      0.55      0.62      1627
           2       1.00      0.00      0.01       586

    accuracy                           0.88     12669
   macro avg       0.87      0.51      0.52     12669
weighted avg       0.88      0.88      0.85     12669

Confusion matrix: 
 [[10255   201     0]
 [  729   898     0]
 [  403   181     2]]


In [8]:
# saving model
import pickle

# Save the trained model as a pickle string.
saved_model = pickle.dump(model, open('/Users/vanshika/SVM', 'wb'))

# Load the pickled model
m_from_pickle = pickle.load(open('/Users/vanshika/SVM', 'rb'))

# Use the loaded pickled model to make predictions
m_from_pickle.predict(X_test)


array([1, 0, 0, ..., 0, 0, 0], dtype=int64)